---

- include: nginx-repo.yml

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: nginx

- name: install nginx package via yum
  yum: name=nginx state=present enablerepo=epel
  when: ansible_os_family == "RedHat"
  tags:
    - nginx
    - nginx-rhel

- name: install nginx package via apt
  apt: name=nginx state=present update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"
  tags:
    - nginx
    - nginx-debian

- name: copy nginx configuration file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- include_tasks: nginx-default.yaml
  when: nginx_default_file = True

- include_tasks: nginx-vhosts.yaml

- include_tasks: nginx-stub.yaml
  when: nginx_stub_file = True

  notify:
   - restart nginx
  tags: nginx

- name: enable nginx service
  service: name=nginx state=started enabled=yes
  tags: 
    - nginx
    - nginx-service
