---

- name: create directories for Debian specific configurations
  file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"
  when: ansible_os_family == "Debian"
  tags:
    - nginx
    - nginx-default

- name: copy nginx default configuration file (Debian)
  template: src=default.conf.j2 dest=/etc/nginx/sites-available/default
  when: ansible_os_family == "Debian"
  tags: nginx

- name: create default link for site enabled specific configurations (Debian)
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
  when: ansible_os_family == "Debian"
  tags: nginx

- name: copy nginx default configuration file (RedHat)
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  when: ansible_os_family == "RedHat"
  tags: nginx

- name: remove default Debian nginx vhost config file (if configured)
  file: path=/etc/nginx/sites-enabled/default state=absent
  when: ansible_os_family == "Debian"
  tags: nginx

- name: remove default RedHat nginx vhost config file (if configured)
  file: path=/etc/nginx/conf.d/default.conf state=absent
  when: ansible_os_family == "RedHat"
  tags: nginx
