---

mysql_user: "mysql"
mysql_port: "3306"

mysql_bind_address:
  - "127.0.0.1"
  - "192.168.0.1"

mysql_skip_name_resolve: true

mysql_max_allowed_packet: "32M"
mysql_max_connections: 256

mysql_query_cache_size: "64M"
mysql_query_cache_limit: "8M"

mysql_join_buffer_size: "32M"
mysql_sort_buffer_size: "2M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "2M"
mysql_tmp_table_size: "64M"

mysql_innodb_buffer_pool_size: 536870912
mysql_innodb_log_file_size: "4096M"
mysql_innodb_flush_method: "O_DIRECT"
