---

worker_connections: 1024

nginx_http_params:
  charset: "utf-8"
  sendfile: "on"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: "65"
  server_tokens: "off"
  client_max_body_size: "32m"

nginx_stub_file: false
nginx_default_file: false

nginx_log_dir: "/var/log/nginx"
nginx_error_log_name: "access.log"
nginx_access_log_name: "error.log"
nginx_default_port: 80

nginx_proxy_pass_params:
  proxy_pass_location: "/"
  proxy_pass_ip: "10.20.30.40"
  proxy_pass_port: 8080
  proxy_pass_scheme: "http"

nginx_vhosts:
  - listen: 80
    server_name: "demo1.teeny.in"
    root: "/var/www/demo1.teeny.in"
    index: "index.php"
    try_files: "$uri $uri/ $uri.php =404"
    nginx_fastcgi_enable: true
    nginx_proxy_pass_enable: false
    nginx_ssl_enable: false
    state: "present"
