---

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - zabbix
    - zabbix-agent

- include: zabbix-repo.yml

- name: install zabbix-agent via yum
  yum: name=zabbix-agent state=installed
  when: ansible_os_family == 'RedHat'
  tags:
    - zabbix
    - zabbix-agent

- name: install zabbix-agent via apt
  apt: name=zabbix-agent state=installed
  when: ansible_os_family == 'Debian'
  tags:
    - zabbix
    - zabbix-agent

- name: create zabbix config file
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644
  notify:
    - restart zabbix-agent
  tags:
    - zabbix
    - zabbix-agent

- name: enable zabbix-agent service
  service: name=zabbix-agent state=started enabled=yes
  when: zabbix_enabled == True
  tags:
    - zabbix
    - zabbix-agent

- include: zabbix-checks.yml
