---
galaxy_info:
  author: Nobody
  description: OpenJDK / Oracle JDK 6, 7 and 8.
  license: No
  min_ansible_version: 1.9.6
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  categories:
  - development
  - system
dependencies: []
