---

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - dhcp-server
    - dhcp

- name: install dhcp-server
  package: pkg={{ item }} state=installed
  with_items: "{{ dhcp_packages }}"
  tags:
    - dhcp-server
    - dhcp

- name: create dhcp config file
  template: src=dhcpd.conf.j2 dest="{{ dhcp_config }}" validate='dhcpd -t -cf %s'
  notify:
    - restart dhcp-server
  tags:
    - dhcp-server
    - dhcp

- name: enable dhcp-server
  service: name="{{ dhcp_service }}" state=started enabled=false
  tags:
    - dhcp-server
    - dhcp
