---

- name: install the epel repo (rhel 7)
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_version == "7"
        and ansible_distribution != "Fedora"
  tags:
    - common
    - epel-repo
 
- name: install the epel repo (rhel 8)
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_version == "8"
        and ansible_distribution != "Fedora"
  tags:
    - common
    - epel-repo
