---

- include: epel-repo.yml

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - common
    - common-rhel
    - common-debian

- name: install common packages via yum
  yum: name="{{ common_packages }}" state=present enablerepo=epel
  when: ansible_os_family == "RedHat"
  tags:
    - common
    - common-rhel

- name: install common apps via apt
  apt: name="{{ common_packages }}" state=present update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"
  tags:
    - common
    - common-debian
